[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"
path = "src/common.rs"

[dependencies]
itertools = "0.13.0"
lexer = "0.1.18"
maplit = "1.0.2"
petgraph = "0.6.5"
regex = "1.11.1"
unicode-segmentation = "1.12.0"
