name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out latest commit
        uses: actions/checkout@v2

      - name: cache crates and target
        uses: Swatinem/rust-cache@v1.0.1

      - name: build
        run: cargo build --verbose

      - name: test
        run: cargo test --verbose
